### ISSUE TITLE
TimeWindow remains same

### ISSUE THREAD

**Issue by daniyalAhmed-code** [googleapis/python-asset#228]
I've been trying to fetch batch_get_history of limited start and end time but the response I'm receiving has all the data beyond the given start and end time.

`window {
  start_time {
    seconds: 1623974419
    nanos: 950810000
  }
  end_time {
    seconds: 9223372036
    nanos: 854775807
  }
}`

This is how I am trying to request the data
```
t = datetime.datetime.now().replace(hour=00, minute=00).timestamp()
    end_time = datetime.datetime.now().replace(hour=23, minute=59).timestamp()
    print(t)
    print(end_time)
    
    seconds = int(t)
    nanos = int(t % 1 * 1e9)
    end_seconds = int(end_time)
    end_nanos = int(end_time % 1 * 1e9)

    start_proto_timestamp = Timestamp(seconds=seconds,nanos=nanos)
    end_proto_timestamp = Timestamp(seconds=end_seconds,nanos=end_nanos)

sset_response = client.batch_get_assets_history(
    
    request={
        "parent": parent,
        "asset_names": asset_names,
        "read_time_window": asset_v1.TimeWindow(start_time = start_proto_timestamp, end_time = end_proto_timestamp),
        "content_type": content_type
    }
    )
```

Can someone please help me out how can I pass TimeWindow in batch_get_history request.
I'm using latest cloudasset plugin with python3.8

**Comment by parthea** [comment]
Hi @daniyalAhmed-code,

I'm sorry that you didn't receive a response.  As a next step, use the `Try this API` section on this [page](https://cloud.google.com/asset-inventory/docs/reference/rest/v1/TopLevel/batchGetAssetsHistory#TimeWindow) to help determine if this is an issue with the API or the client library itself. If the issue also exists when using the `Try this API` tool, then the issue can be escalated to the product team.

**Comment by parthea** [comment]
I'm going to close this issue due to inactivity but please feel free to re-open it with more information.
