### ISSUE TITLE
No info on Github

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [googleapis/python-asset#263]
Github says about the project description:

"About
No description, website, or topics provided."

Setting one gives a good impression about the project

**Comment by busunkim96** [comment]
@parthea Do you have thoughts on a good GH description could be to set across the python repos?

**Comment by parthea** [comment]
Thanks for reporting this @Abdur-rahmaanJ. A description has been added. 

![image](https://user-images.githubusercontent.com/5184014/152650576-c2921abf-400c-4d44-823f-c8e18d0a1264.png)

**Comment by Abdur-rahmaanJ** [comment]
Cool 👍
