### ISSUE TITLE
Samples that depend on BigQuery are not yet compatible with Python 3.10

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-asset#319]
`google-cloud-bigquery` does not yet support Python 3.10. When it does, the 3.10 samples check should turn green. For now, it is OK to merge PRs with a failing 3.10 samples check (the status check is intentionally optional). 

See https://github.com/googleapis/python-bigquery/issues/1006 for the status of python 3.10 support.

**Comment by leahecole** [comment]
Seeing failures in the [3.10 build](https://fusion2.corp.google.com/invocations/5f087468-3ea3-4251-a9d0-8a8d884e5b72/targets/github%2Fpython-asset%2Fsamples%2Fsnippets;config=default/tests) relating to 403s - perhaps this is some latchkey problems?

**Comment by leahecole** [comment]
Added a cloud Asset permission to the service account in the 3.10 specific build project, we'll see if that fixes it

**Comment by leahecole** [comment]
Fixed in #341
