### ISSUE TITLE
Support for python 3.9 and 3.10

### ISSUE THREAD

**Issue by anukaal** [googleapis/python-asset#326]
added support for python 3.9 and 3.10 will work?

**Comment by parthea** [comment]
Hi @anukaal,

I believe it should work however let's keep this issue open until https://github.com/googleapis/python-asset/issues/319 is resolved and the samples tests are passing.

**Comment by leahecole** [comment]
I think that this should be fine now - BigQuery has added support and I just merged in that PR. Please reopen with detailed error messages if you're seeing repeated failures
