### ISSUE TITLE
can't extract output of the "resourses" to csv.

### ISSUE THREAD

**Issue by testgithub-trial** [googleapis/python-asset#345]
I am using python client library files for listing cloud assets. I need to move that output in to csv file. But i can't. because It is showing **TypeError: Object of type Asset is not JSON serializable** 

my code 
```
    response = client.list_assets(
        request={
            "parent": project_resource,
            "read_time": None,
            "asset_types": ["compute.googleapis.com/Instance"],
            "content_type": asset_v1.ContentType.RESOURCE,
            "page_size": 50,
        }
    )
    
    for asset in response:
        print(asset)
        df = json_normalize(asset)  
        df.to_csv('list.csv', sep=',', encoding='utf-8')
``` 

My output
    `TypeError: Object of type Asset is not JSON serializable`
    
**Kindly help it out.**
Do i need to use any other library files to convert to csv??

**Comment by parthea** [comment]
Hi @testgithub-trial,

Please can you try the following which uses [to_dict](https://proto-plus-python.readthedocs.io/en/stable/reference/message.html#proto.message.Message.to_dict) from `proto`? Please see the Inheritance section [here](https://cloud.google.com/python/docs/reference/cloudasset/latest/google.cloud.asset_v1.types.ListAssetsResponse) and related discussion [here](https://github.com/googleapis/python-vision/issues/70#issuecomment-712992731).

```
from google.cloud import asset_v1
from pandas import json_normalize
import proto

project_resource = "projects/{}".format("python-docs-samples-tests-py36")
client = asset_v1.AssetServiceClient()

response = client.list_assets(
    request={
        "parent": project_resource,
        "read_time": None,
        "asset_types": ["compute.googleapis.com/Instance"],
        "content_type": asset_v1.ContentType.RESOURCE,
        "page_size": 50,
    }
)

serializable_assets = [proto.Message.to_dict(asset) for asset in response]
df = json_normalize(serializable_assets)
df.to_csv('list.csv', sep=',', encoding='utf-8')
```

I'm going to close this issue but please feel free to re-open it if you have additional questions.
