### ISSUE TITLE
CloudQuery Asset Inventory Collaboration

### ISSUE THREAD

**Issue by yevgenypats** [googleapis/python-asset#543]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

We maintain a wildly used (for our users) [GCP CloudQuery Source Plugin](https://www.cloudquery.io/docs/plugins/sources/gcp/overview), which supports more than 300 GCP APIs and our users use it to sync their GCP APIs and metadata to various [databases/datalakes)(https://www.cloudquery.io/docs/plugins/destinations/overview).

I've a few questions:

1) If you are interested in helping us maintain the [GCP Plugin](https://github.com/cloudquery/cloudquery/tree/main/plugins/source/gcp), (Similar to how vendors help maintain terraform plugins).
2) Im curious on the underlying implementation of GCP Asset Inventory, and was curious if CloudQuery could be something that you can use internally and this way you can also enable users to export to various other destinations like GCS, BigQuery and others (and you wont need to maintain an asset-inventory that works only with one destination).

**Comment by parthea** [comment]
Thanks for opening this feature request. I'm going to close this issue as it is out of scope of the client library. You could try reaching out to the API team in the [public issue tracker](https://cloud.google.com/support/docs/issue-trackers#trackers-list) for Asset Inventory.
