### ISSUE TITLE
Does this api support partial response? 

### ISSUE THREAD

**Issue by misabhishek** [googleapis/python-asset#57]
I wanted to know if this api can provide partial response explained [here](https://github.com/googleapis/google-api-python-client/blob/master/docs/performance.md#partial-response-fields-parameter).

**Comment by busunkim96** [comment]
@misabhishek Are you using `google-cloud-asset` or `google-api-python-client`?

You can limit the number of resources you get in a call using the scope, query, and asset type. See https://googleapis.dev/python/cloudasset/latest/gapic/v1p1beta1/api.html#

**Comment by misabhishek** [comment]
I am using google-cloud-asset. My question is not related to reducing the
number of resources but the content of the response. Specifically, I only
want the identity from the response of the call to google-cloud-asset. It
is possible to do with some other apis such as resourcemanager using the *field
*arg. I am not sure how to do it with cloud-asset.

Any help would be greatly appreciated.

Thank you,

Abhishek

**Comment by busunkim96** [comment]
Hi,

It doesn't look like there is currently a way to ask for a sub-set of fields using the gRPC API.

**Comment by misabhishek** [comment]
Is it possible to create a feature request for it for gRPC team?

**Comment by busunkim96** [comment]
@misabhishek Could you expand on the motivation for wanting partial fields? I don't think this is supported as omitting fields would violate the message type in many cases.

**Comment by misabhishek** [comment]
One benefit is reducing the network bandwidth. In my case, I only need the
identity field from the asset analyze analyze_iam_policy.

**Comment by busunkim96** [comment]
I see. Since that is a feature request for the product team, please file it [here](https://issuetracker.google.com/savedsearches/559757). Thanks!
