### ISSUE TITLE
testing: A flake in quickstart_listassets_test: test_list_assets

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/python-asset#66]
See:
https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4399

Filtering the query with `"bigquery.googleapis.com/Table"` should stabilize the test.

**Comment by busunkim96** [comment]
@tmatsuo This test kept failing when Sijun was trying to merge #58 so I added a filter `"iam.googleapis.com/Role"` and it seems to be happy now. 😄  https://github.com/googleapis/python-asset/blob/master/samples/snippets/quickstart_listassets_test.py#L26
