### ISSUE TITLE
Can't use page_token in search_all_resources

### ISSUE THREAD

**Issue by venomwaqar** [googleapis/python-asset#83]
I am trying to iterate the `search_all_resources` pager and getting the following exception.

            next_page_token = 0
            while next_page_token is not None:
                params = {
                    "scope": parent
                }
                if next_page_token != 0 and next_page_token is not None:
                    params['page_token'] = next_page_token
                
                response = client.search_all_resources(**params)
                assets = list(response)
                total_assets.append(assets)
                next_page_token = response.next_page_token

> Exception: search_all_resources() got an unexpected keyword argument 'pageToken'

#### Environment details

  - OS type and version:
  - Python version: 3.8
  - google-cloud-asset: 2.0.0

**Comment by busunkim96** [comment]
Hi @venomwaqar,

The method itself doesn't accept `page_token`. If you want to use it, you'll have to create a request object.

```py
from google.cloud import asset

request = asset.SearchAllResourcesRequest(scope=parent, page_token=page_token)
response = client.search_all_resources(request=request)
```

For your use case you might not need to handle the page token manually. The pager can be iterated over. 

```py
from google.cloud import asset

client = asset.AssetServiceClient()
resources = client.search_all_resources(scope=parent)  # <-- this is already an iterable

# to convert into a list
resources = list(resources)

# alternatively you can loop over the pager
for resource in resources:
    print(resource)
```

It may also be helpful to reference the sample: https://github.com/googleapis/python-asset/blob/3219b64c091d60ea62d669ee904517f73b07c0af/samples/snippets/quickstart_searchallresources.py

**Comment by venomwaqar** [comment]
> Hi @venomwaqar,
> 
> The method itself doesn't accept `page_token`. If you want to use it, you'll have to create a request object.
> 
> ```python
> from google.cloud import asset
> 
> request = asset.SearchAllResourcesRequest(scope=parent, page_token=page_token)
> response = client.search_all_resources(request=request)
> ```
> 
> For your use case you might not need to handle the page token manually. The pager can be iterated over.
> 
> ```python
> from google.cloud import asset
> 
> client = asset.AssetServiceClient()
> resources = client.search_all_resources(scope=parent)  # <-- this is already an iterable
> 
> # to convert into a list
> resources = list(resources)
> 
> # alternatively you can loop over the pager
> for resource in resources:
>     print(resource)
> ```
> 
> It may also be helpful to reference the sample: https://github.com/googleapis/python-asset/blob/3219b64c091d60ea62d669ee904517f73b07c0af/samples/snippets/quickstart_searchallresources.py

Hey @busunkim96 thanks for replying.
So you mean this line `resources = list(resources)` will handle the pagination itself when the records are more than 500?

https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Asset.V1/api/Google.Cloud.Asset.V1.SearchAllResourcesRequest.html#Google_Cloud_Asset_V1_SearchAllResourcesRequest_PageSize

**Comment by busunkim96** [comment]
I'm fairly sure it will work - the Pager class is already handling the page token.

https://github.com/googleapis/python-asset/blob/aa153dce2f62c18101472c40964cc3cee9188d78/google/cloud/asset_v1/services/asset_service/pagers.py#L70-L80

**Comment by venomwaqar** [comment]
> I'm fairly sure it will work - the Pager class is already handling the page token.
> 
> https://github.com/googleapis/python-asset/blob/aa153dce2f62c18101472c40964cc3cee9188d78/google/cloud/asset_v1/services/asset_service/pagers.py#L70-L80

Hmmmmm okay. Some of my resources are missing from the result e.g CloudFunctions, so I was in doubt whether it is handling the pagination itself.

**Comment by busunkim96** [comment]
It sounds like things are working as expected, so I'm going to close out this issue. Feel free to open another one if something else pops up.

Thanks!
